### ISSUE TITLE
Implement http_version attribute on BaseResponse object

### ISSUE THREAD

**Issue by StephenBrown2** [encode/http3#106]
Currently, I am utilizing requests, which under the hood uses urllib3, whose [HTTPResponse object](https://github.com/urllib3/urllib3/blob/master/src/urllib3/response.py#L155-L211) contains [a `.version` attribute](https://github.com/urllib3/urllib3/blob/master/src/urllib3/response.py#L218), which is an `int`, ten times greater than the actual HTTP version (i.e. 10 for 1.0, 11 for 1.1, etc).
I currently use it for logging my requests and responses in debug mode.

It would be good I think to implement a similar attribute (either `version` or more specifically `http_version`) for the [BaseResponse](https://github.com/encode/http3/blob/master/http3/models.py#L660) object, for similar purposes, but perhaps use an actual float. What are your thoughts?

Proposal:
`BaseResponse.http_version: float = 0.0  # Could be a floatEnum with known HTTP versions`

**Comment by tomchristie** [comment]
Yup. So we've got `response.protocol`, which is a string and right now can be either `"HTTP/2"` or `"HTTP/1.1"`.

We actually ought to improve on that by using the `.http_version` that `h11` returns in order to return `"HTTP/1.0"` or `"HTTP/0.9"` when appropriate.

Its also possible that we might want to include a `.protocol_value` property which returns tuples such as eg. `(1, 1)` , `(2, 0)`.

**Comment by sethmlarson** [comment]
I think keeping this a string is best due to all the draft versions of QUIC.

**Comment by StephenBrown2** [comment]
Ah perfect. I had seen `.protocol` but clearly missed it in the docs as being exactly what I needed. You can go ahead and close this out unless you'd like to keep it for the discussion on `h11`'s `http_version`

**Comment by tomchristie** [comment]
We might also want to think about switching the name over to `http_version` at some point, since I think that's probably more obvious.

**Comment by tomchristie** [comment]
Alright, we've got "HTTP/1.0" and "HTTP/0.9" detection in there now.

Keep in mind that we might consider switching the API to `http_version` at some point (thoughts on naming, anyone?) so you may want to pin to `0.6.*`.

**Comment by StephenBrown2** [comment]
I wouldn't necessarily switch to `http_version`, as `protocol` makes sense the way that it is now, I'd just mention it in the API [compatibility docs](https://www.encode.io/http3/compatibility/).
