### ISSUE TITLE
Multipart helper

### ISSUE THREAD

**Issue by tomchristie** [encode/http3#11]
The first part of this would be a class that *just* implements taking a files/data dict, and returning the byte-wise multipart content, plus the Content-Type header.

Places to start with this include `urllib3`, and the `requests-toolbelt` streaming multipart encoder.

**Comment by librehat** [comment]
I just found this issue closed with no further comments. I'm currently migrating from `requests` to `httpx` but I don't see what is the replacement of `requests-toolbelt`'s `MultipartEncoder`? There is a convoluted request that I only managed to send with `MultipartEncoder`

**Comment by tomchristie** [comment]
> There is a convoluted request that I only managed to send with MultipartEncoder

You’d need to be providing more details about exactly what you’re not able to do with httpx’s multiparty support in order for us to be able to help at all.

**Comment by florimondmanca** [comment]
Agreed with Tom - right now our multipart support is provided by the `files=...` parameter, which made this issue irrelevant ultimately, but happy to read about situations this doesn’t help you solve fully.

**Comment by librehat** [comment]
So this is what I'm currently sending using `requests`. In short, it is uploading a file to a GQL endpoint (ariadne)

```python
    gql_query = {
    "query": """query (
    $input: Upload!
    ) {...}
    """, "variables": {"input": None} }
    encoder = MultipartEncoder(
        fields={
            "operations": json.dumps(gql_query),
            "map": """{
                "file": ["variables.input"]
            }""",
            "file": ("doc.pdf", open("doc.pdf", "rb"), "application/pdf"),
        }
    )
    requests.post("...", data=encoder, headers={"Content-Type": encoder.content_type})
```

I can make it work with `httpx` by

```python
    httpx.post("...", data=encoder.to_string(), headers={"Content-Type": encoder.content_type})
```

I wasn't able to upload the file with plain `requests` so I used the toolbelt. Maybe I missed an obvious alley for me to do this?

**Comment by florimondmanca** [comment]
Sure, so I think you need to split up between `data=...` (for `operations` and `map`) and `files=...` (for `doc.pdf`), something like this…

```python
data = {
    "operations": json.dumps(gql_query),
    "map": """{
        "file": ["variables.input"]
    }""",
}

files = {
    "file": ("doc.pdf", open("doc.pdf", "rb"), "application/pdf"),
}

response = httpx.post(..., data=data, files=files)
```

The multipart encoding occurs whenever `files=...` is passed and non-empty, so in this case it will use whatever is in `data` as additional fields in the multipart form data.

This behavior is actually not crystal clear in the docs I believe, could probably use a "You can also add additional fields by passing `data=...`" in [Sending Multipart Form Uploads](https://www.python-httpx.org/quickstart/#sending-multipart-file-uploads).
