### ISSUE TITLE
DataField.render_data fails when value is not string

### ISSUE THREAD

**Issue by ambrozic** [encode/http3#119]
DataField only likes `str` objects as values. DataField.render_data will produce an error when ie. `int` or `bytes` objects are part of posted data or form as well as `files`.

```
  File ".../http3/multipart.py", line 29, in render_data
    return self.value.encode("utf-8")
AttributeError: 'int' object has no attribute 'encode'
```

Test to reproduce
```
@pytest.mark.parametrize(("value"), (123, b"abc"))
def test_multipart_non_str(value):
    client = Client(dispatch=MockDispatch())
    data = {"text": value}
    files = {"file": io.BytesIO(b"<file content>")}
    response = client.post("http://127.0.0.1:8000/", data=data, files=files)
    assert response.status_code == 200
```

or code

```
import http3, io

http3.post(
    url="https://httpbin.org/post",
    data={"a": b"1"},
    files={"file": io.BytesIO(b"<file content>")},
)
```

**Comment by tomchristie** [comment]
Okay. Multipart encoded data can *only* handle string or File data. We could perfectly well either coerce a limited set of scalar types, or just coerce any inputs with str()

**Comment by tomchristie** [comment]
Would probably be a useful point of reference to stay in line with whatever urllib3 currently does.

**Comment by ambrozic** [comment]
https://github.com/urllib3/urllib3/blob/master/src/urllib3/filepost.py#L84-L90

urllib3 isn't doing anything particularly advanced either. i can make a PR with a similar solution if you are fine with it.

**Comment by tomchristie** [comment]
So looks like urllib3 only accepts str/byte values. What does requests do for that case? If it coerces to str, then any idea where it does that?

**Comment by ambrozic** [comment]
Most of the fiddly magic in requests happens in [requests.models:_encode_files](https://github.com/kennethreitz/requests/blob/bedd9284c9646e50c10b3defdf519d4ba479e2c7/requests/models.py#L124-L139). Quite a bit of knowledge implemented which can help us. Prepared data is then sent to [urllib.filepost:encode_multipart_formdata](https://github.com/urllib3/urllib3/blob/master/src/urllib3/filepost.py#L63-L98) we've already checked above. 

Another edge case i came across reading this code are `None` values in `data` which would have to be handled in [http3.multipart:multipart_encode](https://github.com/encode/http3/blob/master/http3/multipart.py#L93)

**Comment by tomchristie** [comment]
Okay, so to keep in the with the behaviour I can see there, we should:

* Ignore `None` values.
* Cast any non-str/bytes to str.
* Handle lists of args.

**Comment by sethmlarson** [comment]
I already posted in the PR (didn't realize this was the issue for that PR until looking further down the list) but I'm not a fan of blindly casting objects that are passed in to strings and then shipping that. Why not raise an error in that situation?

**Comment by ambrozic** [comment]
my argument would be that data ends up as string in multipart form body anyway and interface should let user go as far as reasonably possible before raising errors.

**Comment by tomchristie** [comment]
There's no right answer here - either API could be an resonable design choice.

I *think* we should probably prefer to nail things down quite tightly - given that we've got properly typed interfaces all the way through, it'd be nice if we worked towards raising `TypeError` on *any* incorrect type passed to one of our public interfaces.

**Comment by sethmlarson** [comment]
We should strive towards no `typing.Any` usage in public interfaces. :)

**Comment by ambrozic** [comment]
Does this imply this issue is a non-issue then? It already works as expected under current implementation. Should libraries using `http3` convert passed values in `data` dict according to interface?

**Comment by tomchristie** [comment]
I guess there's still *some* issues to be resolved here:

* Ensure we deal with list of str / list of bytes okay.
* Ensure we raise `TypeError` on any dict values other than `bytes|str|typing.List[bytes]|typing.List[str]`.
* Ensure we raise `TypeError` on any dict keys other than `str`.

Slightly depends on exactly which points we intend to perform the type checking at.

**Comment by sethmlarson** [comment]
Can this issue be closed now?
