### ISSUE TITLE
HTTP/2 Upgrade support

### ISSUE THREAD

**Issue by tomchristie** [encode/http3#25]
Currently we only support HTTP/2 on https connections.

Establishing HTTP/2 on http works a little differently in that it starts with a regular HTTP/1.1 connection, and includes an `Upgrade` header. If the server responds with an appropriate upgrade response, then we switch to HTTP/2.

This would require a little bit of work, since we'd need the `HTTP11Connection` class to be able to call back into the `Connection` in order to indicate that an upgrade has been performed.

**Comment by sethmlarson** [comment]
Is this functionality even worth implementing given how all major browsers only implement HTTP/2 over HTTPS? We'll need something like this for QUIC for sure but I'm not sure about HTTP/2.

**Comment by tomchristie** [comment]
Undecided. I think it's probably helpful for some stuff eg. against a local HTTP/2 server, but I certainly don't think it makes the 1.0 cutoff, and it may well not be worthwhile at all.

On the grounds that I think we should try to keep the scope strictly narrowed in on a viable 1.0 release I'm going to close this off.

**Comment by gvbgduh** [comment]
I think it would worth implementing at least to comply with most of the clients as they would try to upgrade to HTTP/2 (_under some circumstances_), but I agree that it should be out of the scope for the 1.0.
And I'll try to help with it as part of the uvicorn progress when it comes to this.
